import React, { useEffect, useState } from 'react'
import {
  Box, Grid, Card, CardContent, CardHeader, Divider, Button, Typography,
  Select, MenuItem, FormControl, InputLabel, Chip, CircularProgress
} from '@mui/material'
import { Assessment, FileDownload, PlayArrow } from '@mui/icons-material'
import { useDispatch, useSelector } from 'react-redux'
import { fetchReports, generateReport, exportReport, selectReports, selectReportLoading, selectReportGenerating } from '../../store/slices/reportSlice'
import { selectUser } from '../../store/slices/authSlice'
import PageHeader from '../../components/common/PageHeader'
import DataTable from '../../components/common/DataTable'

const REPORT_TYPES = ['procurement', 'vendor', 'risk', 'compliance']
const TYPE_COLORS = { procurement: 'primary', vendor: 'info', risk: 'error', compliance: 'success' }

function ReportingCenter() {
  const dispatch = useDispatch()
  const reports = useSelector(selectReports)
  const loading = useSelector(selectReportLoading)
  const generating = useSelector(selectReportGenerating)
  const user = useSelector(selectUser)
  const [selectedType, setSelectedType] = useState('procurement')

  useEffect(() => { dispatch(fetchReports()) }, [dispatch])

  const handleGenerate = async () => {
    await dispatch(generateReport({
      title: `${selectedType.charAt(0).toUpperCase() + selectedType.slice(1)} Report — ${new Date().toLocaleDateString()}`,
      type: selectedType,
      user: user?.name,
      filters: {},
    }))
  }

  const columns = [
    { id: 'title', label: 'Report', minWidth: 250 },
    { id: 'type', label: 'Type', width: 120, render: (val) => <Chip label={val} size="small" color={TYPE_COLORS[val]} /> },
    { id: 'generatedBy', label: 'Generated By', width: 160 },
    { id: 'generatedAt', label: 'Date', width: 130, render: (val) => new Date(val).toLocaleDateString() },
    { id: 'status', label: 'Status', width: 100, render: () => <Chip label="Ready" size="small" color="success" /> },
    {
      id: 'id', label: 'Actions', width: 160, align: 'right',
      render: (val) => (
        <Box sx={{ display: 'flex', gap: 0.5, justifyContent: 'flex-end' }}>
          <Button size="small" startIcon={<FileDownload />} onClick={() => dispatch(exportReport({ id: val, format: 'csv' }))}>CSV</Button>
          <Button size="small" startIcon={<FileDownload />} onClick={() => dispatch(exportReport({ id: val, format: 'xlsx' }))}>Excel</Button>
        </Box>
      )
    },
  ]

  return (
    <Box>
      <PageHeader
        title="Reporting Center"
        subtitle="Generate, view and export enterprise reports"
        breadcrumbs={[{ label: 'Dashboard', href: '/dashboard' }, { label: 'Reports' }]}
      />

      {/* Report Generator */}
      <Card sx={{ mb: 2.5 }}>
        <CardHeader title="Generate New Report" titleTypographyProps={{ variant: 'subtitle1', fontWeight: 600 }} />
        <Divider />
        <CardContent>
          <Box sx={{ display: 'flex', gap: 2, alignItems: 'center', flexWrap: 'wrap' }}>
            <FormControl size="small" sx={{ minWidth: 180 }}>
              <InputLabel>Report Type</InputLabel>
              <Select label="Report Type" value={selectedType} onChange={(e) => setSelectedType(e.target.value)}>
                {REPORT_TYPES.map((t) => (
                  <MenuItem key={t} value={t} sx={{ textTransform: 'capitalize' }}>
                    {t.charAt(0).toUpperCase() + t.slice(1)} Report
                  </MenuItem>
                ))}
              </Select>
            </FormControl>
            <Button
              variant="contained"
              startIcon={generating ? <CircularProgress size={16} sx={{ color: 'white' }} /> : <PlayArrow />}
              disabled={generating}
              onClick={handleGenerate}
            >
              Generate Report
            </Button>
          </Box>
        </CardContent>
      </Card>

      {/* Report List */}
      <Card>
        <CardHeader
          title="Report Library"
          titleTypographyProps={{ variant: 'subtitle1', fontWeight: 600 }}
          subheader="All generated reports"
          subheaderTypographyProps={{ variant: 'caption' }}
        />
        <Divider />
        <CardContent sx={{ p: 0 }}>
          <DataTable columns={columns} rows={reports} loading={loading} total={reports.length} emptyMessage="No reports generated yet." />
        </CardContent>
      </Card>
    </Box>
  )
}

export default ReportingCenter
